image: mcr.microsoft.com/dotnet/sdk:7.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:          # List of stages for jobs, and their order of execution
  - build

build-debug:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - apt update && apt upgrade
    - apt install -y python3 libfreetype6
    - git submodule update --init --recursive
    - mkdir .git/hooks -p
    - dotnet restore
    - dotnet build --configuration Debug --no-restore /p:WarningsAsErrors=nullable /m
    - dotnet test --no-build Content.Tests/Content.Tests.csproj
    - export DOTNET_gcServer=1
    - dotnet test --no-build Content.IntegrationTests/Content.IntegrationTests.csproj

build-release:
  stage: build
  script:
    - apt update && apt upgrade
    - apt install -y python3 libfreetype6
    - git submodule update --init --recursive
    - mkdir .git/hooks -p
    - dotnet restore
    - dotnet build --configuration Release --no-restore /p:WarningsAsErrors=nullable /m
    - dotnet test --no-build Content.Tests/Content.Tests.csproj
    - export DOTNET_gcServer=1
    - dotnet test --no-build Content.IntegrationTests/Content.IntegrationTests.csproj
